#!/bin/bash


videoname=$(get_flash_videos "$1" 2>&1 | grep 'Done.' | awk '{ print $6 }')
filename="${videoname%.*}"
echo -n "Bit rate (kbit/s) (default 320): "
read bitrate
if [ -z "$bitrate" ]
then
    bitrate=320
fi
ffmpeg -i "$videoname" -acodec libmp3lame -ac 2 -ab "$bitrate"k -vn -y "$filename".mp3

